### ISSUE TITLE
Build and publish Snap image for releases

### ISSUE THREAD

**Issue by Doctor-love** [wader/fq#98]
["Snap"](https://en.wikipedia.org/wiki/Snap_(package_manager)) is a popular package format that enables Linux users to install and run applications cross-distro.
In order to help potential users discover and use fq, it would be neat to automatically build and publish a snap during the release process.

fq utilizes [GoReleaser](https://github.com/goreleaser/goreleaser) in [the "release" workflow](https://github.com/wader/fq/blob/master/.github/workflows/release.yml), which [according to the document supports building and publishing snaps](https://goreleaser.com/customization/snapcraft/).

I don't have any experience packaging snaps, so help would be greatly appreciated.

**Comment by Doctor-love** [comment]
How is confinement handled in Snaps? fq should be very easy to restrict (syscalls, network access, etc), except for which file paths it needs to access for probing.

**Comment by wader** [comment]
Yeap i think fq has very basic needs, read filsystem, read/write stdout and stderr maybe some ioctls for readline. All interaction with the os (exceptions for some profiling and fuzz things) are done thru the `stdOS` type https://github.com/wader/fq/blob/master/pkg/cli/cli.go#L36

Maybe first step i get a snap config with good confinement  working and then look into goreleaser things?

I can do -rc tag releases once we have something to try

**Comment by Akaame** [comment]
```yaml
name: fq
summary: jq for binary formats 
description: |
    fq is inspired by the well known jq tool and language and allows you to work with binary formats the same way you would using jq. 
    In addition it can also present data similar to a hex viewer, transform, slice and concatenate binary data, supports nested formats and has an interactive REPL with auto-completion.
version: git
grade: stable
base: core20

confinement: classic # or strict

apps:
  fq:
    command: bin/fq
    plugs:
      - home # should be enough
parts:
  fq:
    plugin: go
    source-type: git
    source: https://github.com/wader/fq
```

Do not have a linux system to test this on but should not something like this be enough for a basic golang based IO program?

**Comment by wader** [comment]
Thanks, i guess one maybe can test via docker or emulated if on some non-snap:able platform? what is needed more, some kind of packaging and publish? @Doctor-love any ideas?

@Akaame BTW I noticed your name didn't show up as contributor on github for fq, maybe git email configured differently somehow?

@Akaame Second BTW if your into binary tools there is a conference going on this weekend https://binary-tools.net/summit.html. I gave a talk about fq yesterday that was recorded so hopefully will show up somewhere soon.

**Comment by Akaame** [comment]
First BTW: I just realized that I committed to this repo using another git profile.
Second BTW: Thanks for the heads-up.

I just realized snapcraft is available on Mac and I already have multipass anyway. Will try if this works and if it does we can simply extend goreleaser.

>  i guess one maybe can test via docker or emulated if on some non-snap:able platform? what is needed more, some kind of packaging and publish? @Doctor-love any ideas?

I think we should not scope creep this particular issue but adding flatpak to out release outputs would also be nice in some other issue.

**Comment by Akaame** [comment]
I finally got snapcraft working on Mac. We have three problems

Snapcraft Go plugin has this line:

https://github.com/snapcore/snapcraft/blob/b81550376df7f2d0dfe65f7bfb006a3107252450/snapcraft/plugins/v1/go.py#L307

Which results in the following statement:

```sh
go install -p 2 -ldflags -linkmode=external ./...
```

However, we want:

```sh
go install -p 2 -ldflags -linkmode=external .
```

Luckily, we have the `override-build` option to handle the build/install however we want to.

```yaml
build-environment:
      - CGO_ENABLED: '0'
override-build: |
      go install -p 2 -trimpath -ldflags "-s -w -linkmode=external" .
```

The second problem is that I had to populate `build-environment` and the line in `override-build` parameters to pass in our build environment variables, flags and ldflags. These values are already a part of goreleaser.yaml and I do not know how to confirm that GoReleaser Snapcraft plugin will indeed pass them along as environment variables so that we do not have to hardcode the flags as I did for `override-build`.  

Third problem is we need to be able to push created snaps to snapstore for which there is this action:
https://github.com/snapcore/action-publish
